export const CREDarkPool = [
	{
		inputs: [
			{ internalType: 'address', name: '_vaultContract', type: 'address' },
			{ internalType: 'address', name: '_policyEngine', type: 'address' },
		],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{ inputs: [], name: 'InvalidPremium', type: 'error' },
	{ inputs: [], name: 'InvalidTimeout', type: 'error' },
	{ inputs: [], name: 'RequestNotFound', type: 'error' },
	{ inputs: [], name: 'RequestNotPending', type: 'error' },
	{ inputs: [], name: 'RequestExpired', type: 'error' },
	{ inputs: [], name: 'NotExpiredYet', type: 'error' },
	{ inputs: [], name: 'TicketAlreadyUsed', type: 'error' },
	{ inputs: [], name: 'InvalidTicket', type: 'error' },
	{ inputs: [], name: 'TransferFailed', type: 'error' },
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ indexed: false, internalType: 'uint256', name: 'premiumBps', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'timeout', type: 'uint256' },
		],
		name: 'CollateralRequested',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ indexed: true, internalType: 'bytes32', name: 'shieldedAddress', type: 'bytes32' },
		],
		name: 'ShieldedAddressGenerated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ indexed: true, internalType: 'bytes32', name: 'shieldedAddress', type: 'bytes32' },
			{ indexed: true, internalType: 'bytes32', name: 'teeAttestation', type: 'bytes32' },
		],
		name: 'ConfidentialFillSubmitted',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ indexed: false, internalType: 'bytes32', name: 'withdrawalTicket', type: 'bytes32' },
		],
		name: 'RequestFilled',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ indexed: true, internalType: 'bytes32', name: 'ticket', type: 'bytes32' },
			{ indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'ConfidentialWithdrawal',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
		],
		name: 'RequestExpired',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'balanceHash', type: 'bytes32' },
			{ indexed: false, internalType: 'uint256', name: 'version', type: 'uint256' },
		],
		name: 'CCCBalanceTableUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'depositId', type: 'bytes32' },
			{ indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		name: 'CCCLiquidityDeposited',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ indexed: false, internalType: 'bool', name: 'recoverySucceeded', type: 'bool' },
			{ indexed: false, internalType: 'bytes32', name: 'balanceHash', type: 'bytes32' },
			{ indexed: false, internalType: 'uint256', name: 'fillCount', type: 'uint256' },
		],
		name: 'CCCSettlementCompleted',
		type: 'event',
	},
	{
		inputs: [
			{ internalType: 'bytes32', name: 'encryptedAmount', type: 'bytes32' },
			{ internalType: 'uint256', name: 'premiumBps', type: 'uint256' },
			{ internalType: 'uint256', name: 'timeout', type: 'uint256' },
			{ internalType: 'bytes32', name: 'shieldedAddress', type: 'bytes32' },
		],
		name: 'requestCollateral',
		outputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'encryptedAmount', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'shieldedAddress', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'teeAttestation', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'withdrawalTicket', type: 'bytes32' },
		],
		name: 'confidentialFill',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes', name: 'encryptedAmount', type: 'bytes' },
		],
		name: 'depositLiquidity',
		outputs: [{ internalType: 'bytes32', name: 'depositId', type: 'bytes32' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ internalType: 'bytes', name: 'encryptedBalances', type: 'bytes' },
			{ internalType: 'bytes32', name: 'balanceHash', type: 'bytes32' },
			{ internalType: 'bool', name: 'recoverySucceeded', type: 'bool' },
			{ internalType: 'uint256', name: 'fillCount', type: 'uint256' },
			{ internalType: 'bytes', name: 'cccAttestation', type: 'bytes' },
		],
		name: 'cccSettle',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
		name: 'getSettlementResult',
		outputs: [
			{ internalType: 'bool', name: 'recoverySucceeded', type: 'bool' },
			{ internalType: 'bytes32', name: 'balanceHash', type: 'bytes32' },
			{ internalType: 'uint256', name: 'fillCount', type: 'uint256' },
			{ internalType: 'uint256', name: 'timestamp', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ internalType: 'address', name: 'token', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			{ internalType: 'bytes32', name: 'ticket', type: 'bytes32' },
		],
		name: 'withdrawWithTicket',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'encryptedAmount', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'shieldedAddress', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'teeAttestation', type: 'bytes32' },
			{ internalType: 'bytes32', name: 'withdrawalTicket', type: 'bytes32' },
			{ internalType: 'bool', name: 'isFinalFill', type: 'bool' },
		],
		name: 'confidentialPartialFill',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
		name: 'expireRequest',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
		name: 'getRequestStatus',
		outputs: [
			{ internalType: 'uint8', name: 'status', type: 'uint8' },
			{ internalType: 'uint256', name: 'timeRemaining', type: 'uint256' },
			{ internalType: 'bool', name: 'hasWithdrawalTicket', type: 'bool' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'token', type: 'address' },
			{ internalType: 'bytes32', name: 'shieldedAddress', type: 'bytes32' },
			{ internalType: 'uint256', name: 'nonce', type: 'uint256' },
		],
		name: 'getApiSignature',
		outputs: [{ internalType: 'bytes32', name: 'digest', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'mm', type: 'address' },
			{ internalType: 'bool', name: 'authorized', type: 'bool' },
		],
		name: 'setMarketMaker',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '_vault', type: 'address' }],
		name: 'setVaultContract',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'emergencyPause',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getBalanceTableInfo',
		outputs: [
			{ internalType: 'bytes32', name: 'balanceHash', type: 'bytes32' },
			{ internalType: 'uint256', name: 'lastUpdated', type: 'uint256' },
			{ internalType: 'uint256', name: 'version', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
		name: 'getNonce',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'incrementNonce',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'vaultContract',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'policyEngine',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'authorizedMarketMakers',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		name: 'usedTickets',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
] as const
